name: Faster Than Python 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  profile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Perf Enable
      run: sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
    - name: Day 1
      run: ./profile/compare_python.sh 01 
    - name: Day 4
      run: ./profile/compare_python.sh 04 
